conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path

from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

dashboard/urls.py
from django.urls import path

from . import views

app_name =  'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views 

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

online_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username*',
        'class': 'cus-class'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password*',
        'class': 'cus-class'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username*',
        'class': 'cus-class'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email*',
        'class': 'cus-class'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password*',
        'class': 'cus-class'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password*',
        'class': 'cus-class'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Catagory, Item


from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    catagories = Catagory.objects.all()

    return render(request, 'core/index.html', {
                  'catagories': catagories,
                  'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
        
    else:
        form = SignupForm()

  

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <title>{% block title %}{% endblock %} | Haantlay</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>



    <nav class="navbar">
        <div id="menu-btn">
            <i class="bi bi-list"></i>
        </div>
        <div class="nav-logo col-md-2">
            <a href="/"><img src="../../static/logo-h.svg" class="logo-img"></a>
        </div>
        <div class="nav-links col-md-10" id="pc-nav">
            <a href="{% url 'item:new' %}">New Item</a>
            <a href="{% url 'item:items' %}">Browse</a>
            <a href="{% url 'conversation:inbox' %}">Inbox</a>
            <a href="{% url 'dashboard:index' %}">Dashboard</a>
            <a href="{% url 'core:login' %}" class="login-icon"><i class="bi bi-person-plus"></i></a>
        </div>
        <div id="mobile-nav">
            <a href="{% url 'core:login' %}" class="login-icon"><i class="bi bi-person-plus"></i></a>
        </div>
      </nav>
      <div id="m-nav">        
          <div id="mobile-nav-links">
            <a href="{% url 'item:new' %}">New Item</a>
            <a href="{% url 'item:items' %}">Browse</a>
            <a href="{% url 'conversation:inbox' %}">Inbox</a>
            <a href="{% url 'dashboard:index' %}">Dashboard</a>
        </div>
      </div>
      
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 copyright">
                    <p>Copyright 2024 Haantlay. All right reserved!</p>
                </div>
            </div>
        </div>
    </footer>

    <script>
        document.getElementById('menu-btn').addEventListener('click', function() {
        var nav = document.getElementById('m-nav');
        if (nav.style.display === 'block') {
            nav.style.display = 'none';
        } else {
            nav.style.display = 'block';
        }
        });
        function hideMenu() {
            var nav = document.getElementById('m-nav');
            nav.style.display = 'none';
        }
        window.addEventListener('scroll', hideMenu);
    </script>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1>The Contact Page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
{% load static %}
    <div>
          <div id="carouselExampleRide" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'im1.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'im2.png' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'im3.png' %}" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleRide" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
    </div>
    
    <div class="search-bar-div col-md-12">
        <div class="search-bar-box">
            <form action="{% url 'item:items' %}" method="get">
                <input type="text" name="query" class="search-bar"  value="{{ query}}" placeholder="Search the product">

                <button class="search-bar-button"><i class="bi bi-search"></i></button>
            </form>
        </div>
    </div>
        <h2 class="head-font">Newest items</h2>
        <div class="container my-5">
          <div class="row row-cols-1 row-cols-md-3 g-3">
              {% for item in items %}
                  <div class="col-lg-3 col-md-6 mb-4">
                    <a href="{% url 'item:detail' item.id %}" class="text-decoration-none text-dark">
                      <div class="card card-custom">
                        <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                        <div class="card-body">
                          <h2 class="card-title h5">{{ item.name }}</h2>
                          <p class="card-text text-muted">Price: {{ item.price }}</p>
                        </div>
                      </div>
                    </a>
                  </div>
                 {% endfor %} 
          </div>
        </div>




        <h2 class="head-font">Catagories</h2>

        <div class="container my-5">
          <div class="row row-cols-1 row-cols-md-3 g-3">
            {% for catagory in catagories %}
            <div class="col">
              <a href="#" class="text-decoration-none text-dark">
                <div class="card cata-card">
                  <div class="card-body cata-body">
                    <h2 class="h5">{{ catagory.name }}</h2>
                    <p class="text-muted">{{ catagory.items.count }} Items</p>
                  </div>
                </div>
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title  %}Log in{% endblock %}

{% block content  %}

<div class="form-c">
    <div class="container">

        <div class="row justify-content-center m-6">
          <div class="col-md-5 form-body">
            <h1 class=" form-text">Log in</h1>
    
            <form action="." method="post">
                {% csrf_token %}
        
                <div class="mb-3">
                    {{ form.username }}
                </div>
        
                <div class="mb-3">
                    {{ form.password }}
                </div>
        
                {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-3 bg-danger text-white rounded">
                    {% for field in form %}
                    {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
                {% endif %}
        
                <p class="form-p">No account?<a href="{% url 'core:signup' %}" class="form-l"> Create one!</a></p>
                <button type="submit" class="form-btn">Submit</button>
            </form>
          </div>
        </div>
    </div>
</div>



{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title  %}Sign up{% endblock %}

{% block content  %}



<div class="form-s">
    <div class="container">

        <div class="row justify-content-center m-6">
          <div class="col-md-5 form-body">
            <h1 class=" form-text">Sign up</h1>
                <form action="." method="post">
                    {% csrf_token %}

                    
                    <div class="mb-3">
                        {{ form.username }}
                    </div>

                    
                    <div class="mb-3">
                        {{ form.email }}
                    </div>

                    <div class="mb-3">
                        {{ form.password1 }}
                    </div>

                    <div class="mb-3">
                        {{ form.password2 }}
                    </div>

                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-3 bg-danger text-white rounded">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}    

                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <p class="form-p">Already signup? <a href="{% url 'core:login' %}" class="form-l"> Login!</a></p>
                    <button type="submit" class="form-btn">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}