conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path

from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

item/urls.py
from django.urls import path

from . import views 

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

online_marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import User


from django.db import models

class Catagory(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name    
    

class Item(models.Model):
    catagory = models.ForeignKey(Catagory, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name    
    

item/forms.py
from django import forms

from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('catagory', 'name', 'description', 'price', 'image',)

        widgets = {
            'catagory': forms.Select(attrs={
                'class': 'cus-classs',
            }),
            'name': forms.TextInput(attrs={

                'class': 'cus-classs'
            }),
            'description': forms.Textarea(attrs={

                'class': 'cus-classs'
            }),
            'price': forms.TextInput(attrs={

                'class': 'cus-classs'
            }),
            'image': forms.FileInput(attrs={

                'class': 'cus-classss'
            })
            
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'cus-classs'
            }),
            'description': forms.Textarea(attrs={
                'class': 'cus-classs'
            }),
            'price': forms.TextInput(attrs={
                'class': 'cus-classs'
            }),
            'image': forms.FileInput(attrs={
                'class': 'cus-classss'
            })
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Catagory, Item


def items(request):

    query = request.GET.get('query', '')
    catagory_id = request.GET.get('catagory', 0)
    catagories = Catagory.objects.all()

    items = Item.objects.filter(is_sold=False)


    if catagory_id:
        items = items.filter(catagory_id=catagory_id)


    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query)) 

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'catagories': catagories,
        'catagory_id': int(catagory_id)
    })



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)

    related_items = Item.objects.filter(catagory=item.catagory, is_sold=False).exclude(pk=pk)[0:3]


    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):

    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })




@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{ item.name }}{% endblock %}

{% block content %}
<div class="pro-d">    
    <div class="container">
        <div class="row">
            <div class="col-md-6 proimage">
                <img src="{{ item.image.url }}" alt="" class="pro-image image-fluid">
            </div>
            <div class="col-md-6 prodetail">
                <h1>{{ item.name }}</h1>
                <p class="pro-p"><strong>Price: </strong>{{ item.price }}</p>
                <p><strong>Username: </strong>{{ item.created_by.username }}</p>
                {% if item.description %}
                    <p class="pro-p-p">
                        <strong class="pro-s">Description</strong> <br> {{ item.description }}
                    </p>
                {% endif %}
                {% if request.user == item.created_by %}                
                    <div class="pro-det-sec">
                        <p>This is your item!</p>
                        <a href="{% url 'item:edit' item.id %}" class="c-e-btn">Edit</a>
                        <a href="{% url 'item:delete' item.id %}" class="c-d-btn">Delete Item</a>
                    </div>
                {% else %}
                    <a href="{% url 'conversation:new' item.id %}" class="c-s-btn">Contact seller</a>
                {% endif %}
            </div>
        </div>
    </div>
    
       

 
          
 

    <h2 class="head-font mt-6">Related items</h2>
    <div class="container my-5">
      <div class="row row-cols-1 row-cols-md-3 g-3">
        {% for item in related_items %}
              <div class="col-lg-3 col-md-6 mb-4">
                <a href="{% url 'item:detail' item.id %}" class="text-decoration-none text-dark">
                  <div class="card card-custom">
                    <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                    <div class="card-body">
                      <h2 class="card-title h5">{{ item.name }}</h2>
                      <p class="card-text text-muted">Price: {{ item.price }}</p>
                    </div>
                  </div>
                </a>
              </div>
             {% endfor %} 
      </div>
    </div>

</div>
</div>
{% endblock %} 

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="form-a">
    <div class="container">

        <div class="row justify-content-center m-6">
          <div class="col-md-9 form-body-b">
            <h1 class=" form-text">{{ title }}</h1>

                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}                                       
                    <div class="mb-3">
                        {{ form.as_p }}
                    </div>                 
                    
                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-3 bg-danger text-white rounded">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}    
                        
                            {{ form.non_field_errors }}
                        
                            
                        </div>
                        {% endif %}
                        <button type="submit" class="form-btnn">Add Item</button>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
<div class="brow-div">
    <div class="search-bar-div col-md-12">
        <div class="search-bar-box">
            <form action="{% url 'item:items' %}" method="get">
                <input type="text" name="query" class="search-bar"  value="{{ query}}" placeholder="Search the product">

                <button class="search-bar-button"><i class="bi bi-search"></i></button>
            </form>
        </div>
    </div>
    <div class="container my-5">
        <p class="Cata-font">Sort by categories</p>
        <div class="row">
          {% for catagory in catagories %}
            <div class="col-md-4">
              <ul>
                <li class="{% if catagory.id == catagory_id %} cus-bg{% endif %} c-box">
                  <a href="{% url 'item:items' %}?query={{ query }}&catagory={{ catagory.id}}">{{ catagory.name }}</a>
                </li>
                
              </ul>
            </div>
          {% endfor %}
        </div>
        <a href="{% url 'item:items' %}" class="c-btn">Clear filters</a>
      </div>
    </div> 
    <div class="container my-5">
        <div class="row row-cols-1 row-cols-md-3 g-3">
            {% for item in items %}
                <div class="col-lg-3 col-md-6 mb-4">
                <a href="{% url 'item:detail' item.id %}" class="text-decoration-none text-dark">
                    <div class="card card-custom">
                    <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.name }}">
                    <div class="card-body">
                        <h2 class="card-title h5">{{ item.name }}</h2>
                        <p class="card-text text-muted">Price: {{ item.price }}</p>
                    </div>
                    </div>
                </a>
                </div>
            {% endfor %} 
        </div>
    </div>   
    
       
{% endblock %}